config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :stores
  resources :receipts
  devise_for :users

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :groups
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authenticated_controller.rb
class AuthenticatedController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < AuthenticatedController
  before_action :set_receipt, only: [:show, :edit, :update, :destroy]

  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(receipt_params)

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1
  # PATCH/PUT /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to receipts_url, notice: 'Receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
      params.require(:receipt).permit(:shopping_date)
    end
end

app/controllers/stores_controller.rb
class StoresController < AuthenticatedController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    binding.pry
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/home/index.html.haml
.page-header
  %h1 Home#index
%p Find me in app/views/home/index.html.erb

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title Starter Template for Bootstrap
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <haml_loud> javascript_include_tag &quot;https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js&quot;, &quot;https://oss.maxcdn.com/respond/1.4.2/respond.min.js&quot; </haml_loud>
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Project name", "#", class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"} Home
            %li
              %a{:href => "#about"} About
            %li
              %a{:href => "#contact"} Contact
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{"data-dismiss" => "alert", :type => "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only Close
          = msg
      = yield

app/views/receipts/_form.html.haml
= form_for(@receipt, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @receipt.errors.any?
    .alert.alert-danger.alert-dismissable{:role => "alert"}
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      %h4
        = pluralize(@receipt.errors.count, "error")
        prohibited this receipt from being saved:
      %ul
        - @receipt.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :shopping_date, class: "col-sm-2 control-label"
    .col-sm-10
      = f.date_select :shopping_date, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/receipts/edit.html.haml
.page-header
  = link_to receipts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @receipt, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing receipt
= render 'form'

app/views/receipts/index.html.haml
.page-header
  = link_to new_receipt_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Receipt
  %h1 Listing receipts
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Shopping date
        %th
        %th
        %th
    %tbody
      = content_tag_for(:tr, @receipts) do |receipt|
        %td= receipt.shopping_date
        %td= link_to 'Show', receipt
        %td= link_to 'Edit', edit_receipt_path(receipt)
        %td= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' }

app/views/receipts/new.html.haml
.page-header
  = link_to receipts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New receipt
= render 'form'

app/views/receipts/show.html.haml
.page-header
  = link_to receipts_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_receipt_path(@receipt), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show receipt
%dl.dl-horizontal
  %dt Shopping date:
  %dd= @receipt.shopping_date

app/views/stores/_form.html.haml
= form_for(@store, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @store.errors.any?
    .alert.alert-danger.alert-dismissable{:role => "alert"}
      %button.close{"data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
        %span.sr-only Close
      %h4
        = pluralize(@store.errors.count, "error")
        prohibited this store from being saved:
      %ul
        - @store.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/stores/edit.html.haml
.page-header
  = link_to stores_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @store, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing store
= render 'form'

app/views/stores/index.html.haml
.page-header
  = link_to new_store_path, class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Store
  %h1 Listing stores
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th
        %th
        %th
    %tbody
      = content_tag_for(:tr, @stores) do |store|
        %td= store.name
        %td= link_to 'Show', store
        %td= link_to 'Edit', edit_store_path(store)
        %td= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' }

app/views/stores/new.html.haml
.page-header
  = link_to stores_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New store
= render 'form'

app/views/stores/show.html.haml
.page-header
  = link_to stores_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_store_path(@store), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show store
%dl.dl-horizontal
  %dt Name:
  %dd= @store.name